language: ruby
cache:
  bundler: true
  apt: true
  directories:
    - /var/lib/docker
git:
  strategy: clone
  depth: 1
  quiet: true
stages:
  - test
  - deploy
jobs:
  include:
  - name: Tests
    stage: test
    script: docker exec fse_webapp bundle exec rspec spec
    env:
      - DOCKER_COMPOSE_VERSION: 1.26.0
      - RAILS_ENV: test
      - secure: ipyRUUUrui3JR1F/freGbdT8NIzGMkU3UaIoL1HwXm3Pq0WpX3pi5q6jScDJD4eMmg8pnw2jFd1JQtl379aCYOM2f2r/1VSLugGgE1envF9YXTXelmlp0Vry8Ku+EtpMEujfx01m51ZU75mh4st1k2+Xw9af9gFgX6weBgCzNBN9+R94/YO7Y4DWx7zkRtmfL50Ur9QML4h1FzIC8m+VXz0WTB1CkTd2+mMv2duNaHR5xUiwUFcBJ0TwxlD2NmbSA9egx7q0cdvMTPBmwTPFNVFePpffdv5rft5mr2un5kC1EQCHWmpF0QvDrYpjTcUu6/Yupwoimbaeo5RO4Vm5eub00VwhKgFXhsqukEqv/9V6jGri3xUBLuSXDUP/B7mOa7wUcfB+HhEuI5uoUotRJBcPaTbIm4Y3iTegxZZwQJyFSMTNyeb2n7tOOl2K5l8/vkfdOf8TV8XNQxP68RcVDiJJcq3A5Kb1KLFxX3ZwE9wpxnkLYTtZ+YbM+h8tCorpCJi1AAAYoQvKAZQiSCL9NWL5Q7exhB77nU1Gt1Bq4u86+uxXgoh19f4HenRtlR7mSM+HyHby5cEA8EPq5uWRxDFIZOEuMgrJzpM7OM92j6FpKOJL6sk+k3pZ0TLdh8yN5FJ47xI31tciAl6B3QNw5DE3nSwbd4v/M36PgLUo7k4=
    services:
      - docker
    before_install:
      - sudo apt-get update
      - sudo rm /usr/local/bin/docker-compose
      - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin
    install:
      - docker-compose pull
      - sudo mkdir -p tmp
      - sudo chmod -R 777 .
      - docker-compose up -d
      - docker ps
    before_script:
    - docker exec fse_webapp scripts/wait-for-it.sh localhost:3000 -t 300
  - name: Deployment
    stage: depoy
    before_install:
      - openssl aes-256-cbc -K $encrypted_d8f27d088093_key -iv $encrypted_d8f27d088093_iv -in id_fse_rsa.enc -out id_fse_rsa -d
    install:
      - gem install capistrano
      - gem install capistrano-bundler
      - gem install capistrano-passenger
      - gem install capistrano-rails
      - gem install capistrano-rbenv
      - gem install i18n-1.8.2
    script: bundle exec cap ${TRAVIS_BRANCH/master/production} deploy BRANCH=$TRAVIS_BRANCH
