version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./tmp/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: twinktwerk
      MYSQL_DATABASE: fse_virtual
      MYSQL_USER: fse_user
      MYSQL_PASSWORD: twinktwerk
    networks:
      rails-network:
        aliases:
          - mysql
          - db
  webpacker:
    container_name: webpacker
    image: ethenry/fse_virtual_dev
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/fse_virtual
    environment:
      MYSQL_PASS: twinktwerk
      MYSQL_DATABASE: fse_virtual
      MYSQL_USER: fse_user
      MYSQL_HOST: db
      RAILS_ENV: development
    ports:
      - 3035:3035
    networks:
      rails-network:
        aliases:
          - packer
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      rails-network:
        aliases:
          - queue
  web:
    container_name: fse_webapp
    build:
      context: .
    image: ethenry/fse_virtual_dev
    command: ["./scripts/wait-for-it.sh", "db:3306", "--", "./scripts/start_rails.sh"]
    volumes:
      - .:/fse_virtual
    environment:
      - MYSQL_PASS=twinktwerk
      - MYSQL_DATABASE=fse_virtual
      - MYSQL_USER=fse_user
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - RAILS_ENV
      - RAILS_MASTER_KEY
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
    networks:
      rails-network:
        aliases:
          - web.com
  chrome:
    image: selenium/standalone-chrome-debug:3.9.1-actinium
    ports:
      - "4444:4444"
      - "5900:5900"
    depends_on:
      - web
    networks:
      rails-network:
        aliases:
          - chrome.com
volumes:
  redis-data:
networks:
  rails-network:

