 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/affiliates", type: :request do
  # Affiliate. As you add validations to Affiliate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Affiliate.create! valid_attributes
      get affiliates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      affiliate = Affiliate.create! valid_attributes
      get affiliate_url(affiliate)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_affiliate_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      affiliate = Affiliate.create! valid_attributes
      get edit_affiliate_url(affiliate)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Affiliate" do
        expect {
          post affiliates_url, params: { affiliate: valid_attributes }
        }.to change(Affiliate, :count).by(1)
      end

      it "redirects to the created affiliate" do
        post affiliates_url, params: { affiliate: valid_attributes }
        expect(response).to redirect_to(affiliate_url(Affiliate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Affiliate" do
        expect {
          post affiliates_url, params: { affiliate: invalid_attributes }
        }.to change(Affiliate, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post affiliates_url, params: { affiliate: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested affiliate" do
        affiliate = Affiliate.create! valid_attributes
        patch affiliate_url(affiliate), params: { affiliate: new_attributes }
        affiliate.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the affiliate" do
        affiliate = Affiliate.create! valid_attributes
        patch affiliate_url(affiliate), params: { affiliate: new_attributes }
        affiliate.reload
        expect(response).to redirect_to(affiliate_url(affiliate))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        affiliate = Affiliate.create! valid_attributes
        patch affiliate_url(affiliate), params: { affiliate: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested affiliate" do
      affiliate = Affiliate.create! valid_attributes
      expect {
        delete affiliate_url(affiliate)
      }.to change(Affiliate, :count).by(-1)
    end

    it "redirects to the affiliates list" do
      affiliate = Affiliate.create! valid_attributes
      delete affiliate_url(affiliate)
      expect(response).to redirect_to(affiliates_url)
    end
  end
end
