 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/endorsements", type: :request do
  # Endorsement. As you add validations to Endorsement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Endorsement.create! valid_attributes
      get endorsements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      endorsement = Endorsement.create! valid_attributes
      get endorsement_url(endorsement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_endorsement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      endorsement = Endorsement.create! valid_attributes
      get edit_endorsement_url(endorsement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Endorsement" do
        expect {
          post endorsements_url, params: { endorsement: valid_attributes }
        }.to change(Endorsement, :count).by(1)
      end

      it "redirects to the created endorsement" do
        post endorsements_url, params: { endorsement: valid_attributes }
        expect(response).to redirect_to(endorsement_url(Endorsement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Endorsement" do
        expect {
          post endorsements_url, params: { endorsement: invalid_attributes }
        }.to change(Endorsement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post endorsements_url, params: { endorsement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested endorsement" do
        endorsement = Endorsement.create! valid_attributes
        patch endorsement_url(endorsement), params: { endorsement: new_attributes }
        endorsement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the endorsement" do
        endorsement = Endorsement.create! valid_attributes
        patch endorsement_url(endorsement), params: { endorsement: new_attributes }
        endorsement.reload
        expect(response).to redirect_to(endorsement_url(endorsement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        endorsement = Endorsement.create! valid_attributes
        patch endorsement_url(endorsement), params: { endorsement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested endorsement" do
      endorsement = Endorsement.create! valid_attributes
      expect {
        delete endorsement_url(endorsement)
      }.to change(Endorsement, :count).by(-1)
    end

    it "redirects to the endorsements list" do
      endorsement = Endorsement.create! valid_attributes
      delete endorsement_url(endorsement)
      expect(response).to redirect_to(endorsements_url)
    end
  end
end
